= Loomania

*Loomania* is a project that provides access to selected internals of virtual threads and continuations for the purposes of experimenting with APIs that are not (yet) public within the Loom system.

== Usage

The Loomania JAR can be included in any project compiled against Java 11 or later, however it will only function if the JVM is Java 19.

Furthermore, the following flags must be given on the command line:

* `--enable-preview` - this enables the Loom/virtual thread features
* `--add-opens=java.base/java.lang=ALL-UNNAMED` - this allows the library to hack into the virtual thread internals
* `--add-opens=jdk.internal.vm/java.lang=ALL-UNNAMED` - this allows the library to hack into yet more virtual thread internals

Without *all* of these flags, any Loomania operation will fail by throwing `UnsupportedOperationException`.

=== Usage in production

*DO NOT* use Loomania in production. It's only for experimentation! If the experiments work out, then some or all of these APIs may be added to OpenJDK and this library will go away.

=== The code

To use Loomania, use methods on the `io.github.dmlloyd.loomania.Loomania` class.

* `isInstalled()` - returns `true` if Loomania is usable in the current process.
* `isVirtual(Thread)` - returns `true` iff the given thread is virtual.
* `currentCarrierThread()` - returns the current carrier thread if the current thread is virtual, or the current thread otherwise.
* `enterVirtuality(Consumer<VirtualThreadManager>)` - makes the current thread into a carrier thread, executing the given consumer in a virtual thread. The carrier continues to run until `VirtualThreadManager#close()` is called, at which point it will (theoretically) drain the remaining virtual threads from the pool and cause the outer `enterVirtuality()` call to return.
* `doPinned()` - runs the given code block with the virtual thread pinned to the carrier (preventing preemption).

More complete https://dmlloyd.github.io/loomania/apidocs[API JavaDoc can be found here].

==== The example

This trivial example can be run using `jshell` like this:

```console
$ jshell --class-path path/to/loomania-1.1.jar \
    --enable-preview \
    -R--add-opens=java.base/java.lang=ALL-UNNAMED \
    -R--add-opens=jdk.internal.vm/java.lang=ALL-UNNAMED

|  Welcome to JShell -- Version 19-beta
|  For an introduction type: /help intro

jshell> import io.github.dmlloyd.loomania.*

jshell> Loomania.enterVirtuality(vtm -> vtm.execute(() -> { System.out.println("hello!"); vtm.close();}))
hello!

jshell>
```

Note that without the `close` call, the call to `enterVirtuality` will never return.

== Maven

The maven artifact coordinates are:

```xml
<dependency>
    <groupId>io.github.dmlloyd</groupId>
    <artifactId>loomania</artifactId>
    <version>1.1</version>
</dependency>
```
